Random runner updates
CosmoStat/shapepipe pull request #573
Opened 2022-06-29 07:39 UTC by martinkilbinger

## Summary

- Added options to output mask as healpix FITS image.
- Removed reading and use of list of all tiles for overlapping region detection

## Reviewer Checklist

> Reviewers should tick the following boxes before approving and merging the PR.

- [ ] The PR targets the `develop` branch
- [ ] The PR is assigned to the developer
- [ ] The PR has appropriate labels
- [ ] The PR is included in appropriate projects and/or milestones
- [ ] The PR includes a clear description of the proposed changes
- [ ] If the PR addresses an open issue the description includes "closes #<ISSUE NUMBER>"
- [ ] The code and documentation style match the current standards
- [ ] Documentation has been added/updated consistently with the code
- [ ] All CI tests are passing
- [ ] API docs have been built and checked at least once (if relevant)
- [ ] All changed files have been checked and comments provided to the developer
- [ ] All of the reviewer's comments have been satisfactorily addressed by the developer

2022-06-29 07:53 UTC, sfarrens commented on shapepipe/modules/random_cat_package/random_cat.py
> +        header : FITS header
These don't look like real data types

2022-06-29 07:53 UTC, sfarrens commented on shapepipe/modules/random_cat_package/random_cat.py
> +        print('MKDEBUG', tile_id, file_number_string)
I guess this is to be removed

2022-07-05 08:23 UTC, sfarrens requested changes

2022-07-05 08:23 UTC, sfarrens commented on shapepipe/modules/random_cat_package/random_cat.py
> +        Parameters for healpix output mask file
```suggestion
        Parameters for HEALPix output mask file
```

2022-07-05 08:23 UTC, sfarrens commented on shapepipe/modules/random_cat_package/random_cat.py
> +            image header with WCS information
```suggestion
            Image header with WCS information
```

2022-09-07 07:53 UTC, martinkilbinger commented on shapepipe/modules/random_cat_package/random_cat.py
> +        header : FITS header
how about now?

2022-09-07 07:53 UTC, martinkilbinger commented on shapepipe/modules/random_cat_package/random_cat.py
> +        print('MKDEBUG', tile_id, file_number_string)
removed

2022-09-07 09:08 UTC, sfarrens commented
Hey @martinkilbinger can you just need to fix these minor formatting errors, then the CI tests should pass.

```
______________________________ pycodestyle-check _______________________________
/home/runner/work/shapepipe/shapepipe/shapepipe/modules/mask_package/mask.py:237:12: E275 missing whitespace after keyword

______________________________ pycodestyle-check _______________________________
/home/runner/work/shapepipe/shapepipe/shapepipe/modules/setools_package/setools.py:656:18: E275 missing whitespace after keyword

______________________________ pycodestyle-check _______________________________
/home/runner/work/shapepipe/shapepipe/shapepipe/pipeline/file_io.py:554:24: E275 missing whitespace after keyword
```

2022-09-07 09:12 UTC, martinkilbinger commented
> Hey @martinkilbinger can you just need to fix these minor formatting errors, then the CI tests should pass.
> 
> ```
> ______________________________ pycodestyle-check _______________________________
> /home/runner/work/shapepipe/shapepipe/shapepipe/modules/mask_package/mask.py:237:12: E275 missing whitespace after keyword
> 
> ______________________________ pycodestyle-check _______________________________
> /home/runner/work/shapepipe/shapepipe/shapepipe/modules/setools_package/setools.py:656:18: E275 missing whitespace after keyword
> 
> ______________________________ pycodestyle-check _______________________________
> /home/runner/work/shapepipe/shapepipe/shapepipe/pipeline/file_io.py:554:24: E275 missing whitespace after keyword
> ```

Done, it should pass all tests now.

2022-09-08 16:06 UTC, merged