Updated docs and references
CosmoStat/shapepipe pull request #579
Opened 2022-07-05 10:27 UTC by sfarrens

## Summary

- Updated references to key ShapePipe papers
- Moved notes to margin
- Updated documentation style

## Reviewer Checklist

> Reviewers should tick the following boxes before approving and merging the PR.

- [ ] The PR targets the `develop` branch
- [ ] The PR is assigned to the developer
- [ ] The PR has appropriate labels
- [ ] The PR is included in appropriate projects and/or milestones
- [ ] The PR includes a clear description of the proposed changes
- [ ] If the PR addresses an open issue the description includes "closes #<ISSUE NUMBER>"
- [ ] The code and documentation style match the current standards
- [ ] Documentation has been added/updated consistently with the code
- [ ] All CI tests are passing
- [ ] API docs have been built and checked at least once (if relevant)
- [ ] All changed files have been checked and comments provided to the developer
- [ ] All of the reviewer's comments have been satisfactorily addressed by the developer

2022-07-05 10:43 UTC, sfarrens commented
@martinkilbinger you can find the [latest HTML build here](https://github.com/CosmoStat/shapepipe/suites/7220283116/artifacts/289292576).

2022-07-06 07:20 UTC, martinkilbinger requested changes

2022-07-06 07:20 UTC, martinkilbinger commented on docs/source/module_develop.md
> +If no `stdout` or `stderr` are provided by the given module, the the module
```suggestion
If no `stdout` or `stderr` are provided by the given module, the module
```

2022-07-06 07:40 UTC, martinkilbinger approved these changes

2022-07-06 07:47 UTC, merged