file_io handles sextractor header
CosmoStat/shapepipe pull request #670
Opened 2023-12-12 17:45 UTC by lbaumo

## Summary

> This allows get_header in file_io to convert the fits_ldac header, stored as a binary table, from sextractor to a dictionary. It also corrects the documentation for get_header.  This is the first step in addressing #632 as well as #616 and #604. 

## Reviewer Checklist

> Reviewers should tick the following boxes before approving and merging the PR.

- [ ] The PR targets the `develop` branch
- [ ] The PR is assigned to the developer
- [ ] The PR has appropriate labels
- [ ] The PR is included in appropriate projects and/or milestones
- [ ] The PR includes a clear description of the proposed changes
- [ ] If the PR addresses an open issue the description includes "closes #<ISSUE NUMBER>"
- [ ] The code and documentation style match the current standards
- [ ] Documentation has been added/updated consistently with the code
- [ ] All CI tests are passing
- [ ] API docs have been built and checked at least once (if relevant)
- [ ] All changed files have been checked and comments provided to the developer
- [ ] All of the reviewer's comments have been satisfactorily addressed by the developer

2023-12-13 10:19 UTC, martinkilbinger requested changes
Looks good, maybe you can run `black` on the modified files for automatic formatting.

2023-12-13 10:33 UTC, lbaumo commented
what is going on with the CI tests? It looks like installation is failing.

2023-12-13 10:37 UTC, martinkilbinger commented
> what is going on with the CI tests? It looks like installation is failing.

Looks like a version conflict between numba and numpy. I had to upgrade numpy to a newer version due to some conda errors. Try to set numba=0.58.1.

There might be other CI errors, this has not been working for quite some time.

2026-07-16 14:25 UTC, martinkilbinger commented
no longer needed, https://github.com/CosmoStat/shapepipe/pull/740 has implemented reading of external cats

2026-07-16 14:25 UTC, closed without merging